appname: "Dagobah"
feeds:
    - "http://spf13.com/index.xml"
    - "http://dave.cheney.net/feed"
    - "http://www.goinggo.net/feeds/posts/default"
    - "http://blog.labix.org/feed"
    - "http://blog.golang.org/feed.atom"
